export const state = {
    scene: null,
    camera: null,
    renderer: null,
    controls: null,
    buildings: [],
    labels: [],
    raycaster: null,
    mouse: null,
    buildingGroups: [],
    cars: [],
    clouds: [],
    bugs: [],
    bugsVisible: true,
    testBuildings: [],
    testsVisible: true,
    isNightMode: false,
    sunLight: null,
    ambientLight: null,
    hemisphereLight: null,
    currentScale: 1.0,
    currentData: null,
    availableFiles: [],
    highlightedBuilding: null,
    originalMaterials: new Map(),
    frameCount: 0,
    lastFpsUpdate: 0,
    currentFps: 0,
    rainParticles: null,
    snowParticles: null,
    rainVisible: false,
    snowVisible: false,
    smokeParticles: [],
    smokeVisible: false,
    people: []
};

export const MAX_BUILDINGS = 500;
